name: Tests monstrelib 🧪

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout le code
      uses: actions/checkout@v3

    - name: 📦 Installer Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: ⚙️ Installer uv et les dépendances
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv pip install pytest

    - name: ✅ Lancer les tests
      run: |
        python -m pytest
